"""
IMMUTABLE SAFETY CONSTANTS
===========================
These values are HARDCODED and must NEVER be changed without:
  1. Regenerating safety.hash  (python scripts/seal_safety.py)
  2. A conscious human decision with full understanding of consequences

The engine verifies the SHA-256 hash of this file at startup.
Any modification — even whitespace — will halt the engine until
the hash is regenerated by a human operator.

DO NOT modify these values programmatically or from user input.
"""

# ---------------------------------------------------------------------------
# POSITION LIMITS
# ---------------------------------------------------------------------------

# Maximum fraction of total portfolio in any single ticker (5%)
MAX_POSITION_FRACTION = 0.05

# Maximum fraction of portfolio allocated to a single strategy (30%)
MAX_STRATEGY_ALLOCATION = 0.3

# Maximum fraction in meme stocks specifically (extra risky) (10%)
MAX_MEME_ALLOCATION = 0.1

# Maximum fraction for any single meme stock (extra risky) (2%)
MAX_MEME_POSITION_FRACTION = 0.02

# Minimum stock price — refuse to trade penny stocks below this
MIN_STOCK_PRICE = 1.0  # USD

# ---------------------------------------------------------------------------
# LOSS CIRCUIT BREAKERS
# ---------------------------------------------------------------------------

# Level 1: Reduce position sizes 50%, send alert
CIRCUIT_BREAKER_L1_DAILY_LOSS = 0.02   # 2% portfolio loss in one day

# Level 2: Halt all NEW orders, send alert
CIRCUIT_BREAKER_L2_DAILY_LOSS = 0.03   # 3% portfolio loss in one day

# Level 3: Full halt, require signed human restart token
CIRCUIT_BREAKER_L3_DRAWDOWN  = 0.10   # 10% drawdown from peak ever

# Intraday volatility: auto-exit any position that moves this much
MAX_INTRADAY_POSITION_MOVE = 0.15  # 15%

# VIX threshold: reduce all position sizes by 50% when VIX is above this
HIGH_VIX_THRESHOLD = 40.0

# ---------------------------------------------------------------------------
# ORDER RATE LIMITS
# ---------------------------------------------------------------------------

MAX_ORDERS_PER_MINUTE = 5
MAX_ORDERS_PER_DAY    = 50

# ---------------------------------------------------------------------------
# LEVERAGE & INSTRUMENT RESTRICTIONS
# ---------------------------------------------------------------------------

MAX_LEVERAGE        = 1.0   # Never use margin (1x = cash only)
SHORT_SELLING       = True  # Absolutely no shorting
OPTIONS_WRITING     = False  # No selling options
FUTURES_TRADING     = True
CRYPTO_TRADING      = False  # Paper phase: equities only

# ---------------------------------------------------------------------------
# LIVE TRADING GATE
# ---------------------------------------------------------------------------

# Live trading can NEVER be enabled by the bot itself.
# It requires LIVE_TRADING_ENABLED=true in .env AND a valid APPROVAL_TOKEN_HASH.
# This flag is a reminder — the actual check is in core/safety.py.
LIVE_TRADING_REQUIRES_HUMAN = True

# ---------------------------------------------------------------------------
# AUDIT
# ---------------------------------------------------------------------------

# Audit logs are append-only; the bot never deletes or overwrites them
AUDIT_LOG_APPEND_ONLY = True
AUDIT_LOG_DIR         = "logs/audit"
